name       : haskell-cryptonite-conduit
version    : 0.2.2
release    : 2
source     :
    - http://hackage.haskell.org/package/cryptonite-conduit-0.2.2/cryptonite-conduit-0.2.2.tar.gz : 705d69ab3f79b7b8810c7b9e7da81a1c6686b6a4323b1e78150576a25a658dae
license    : BSD-3-Clause
component  : programming.haskell
summary    : Conduit bridge for cryptonite
description: |
    Conduit bridge for cryptonite
builddeps  :
    - haskell-cabal-install
    - haskell-conduit-extra-devel
    - haskell-cryptonite-devel
rundeps    :
    - devel:
        - haskell-conduit-extra-devel
        - haskell-cryptonite-devel
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
